[project]
name = "control-flow"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jeremiah Lowin", email = "153965+jlowin@users.noreply.github.com" }
]
dependencies = [
    "marvin>=2.3.1",
    "prefect>=2.16.8",
    "pydantic>=2",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipython>=8.22.2",
    "pdbpp>=0.10.3",
    "pre-commit>=3.7.0",
    "ruff>=0.3.4",
    "pytest>=8.1.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/control_flow"]

# ruff configuration
[tool.ruff]
target-version = "py311"
lint.extend-select = ["I"]
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$" # default, but here in case we want to change it

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ['I', 'F401', 'E402']
"conftest.py" = ["F401", "F403"]
'tests/fixtures/*.py' = ['F403']
